# Basic
title: 张忠钢
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: zhzhgang
# 头像里面的描述
avatarDesc: Java / 云计算
url: "http://www.zhzhgang.com"

# Comment
comment:
    # disqus: zhzhgang
    # duoshuo: zhzhgang
    uyan: 2128715

# Social
social:
    weibo: 2321674383 
    github: zhzhgang
    # twitter: 
    zhihu: zhzhgang
    mail: zhang_zhonggang@163.com


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 分类, description: categories, url: '/categories'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


